### ISSUE TITLE
[1.16] NoSuchMethodError on launch dedicated server

### ISSUE THREAD

**Issue by CplPibald** [DavD729/AppleTreesRev#8]
using AppleTreeRev-Fabric-1.16.5-v2.3.jar
on Fabric 0.7.4
MC 1.16.5

Dedicated server crashes early on launch with NoSuchMethodError

```
[00:08:23] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'appletreesrev'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.class_2378.method_10250(Lnet/minecraft/class_2960;)Z
        at dav.mod.world.gen.TreeWorldGen.lambda$registerFeatureToBiomes$0(TreeWorldGen.java:82) ~[AppleTreesRev-Fabric-1.16.5-v2.3.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_181]
        at dav.mod.world.gen.TreeWorldGen.registerFeatureToBiomes(TreeWorldGen.java:80) ~[AppleTreesRev-Fabric-1.16.5-v2.3.jar:?]
        at dav.mod.world.gen.TreeWorldGen.registerFeatures(TreeWorldGen.java:74) ~[AppleTreesRev-Fabric-1.16.5-v2.3.jar:?]
        at dav.mod.AppleTreesRev.registerFeatures(AppleTreesRev.java:35) ~[AppleTreesRev-Fabric-1.16.5-v2.3.jar:?]
        at dav.mod.AppleTreesRev.onInitialize(AppleTreesRev.java:27) ~[AppleTreesRev-Fabric-1.16.5-v2.3.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
        ... 17 more
```

**Comment by DavD729** [comment]
I'll be working on this problem, just To check, Try to use Fabric Loader 0.11.3+, as this was Built on 0.11.6

**Comment by CplPibald** [comment]
Sorry, I'm new to running Fabric.  The server is using whatever is on fabricmc.net as of about 12 hours ago.  It says the *installer* version is 0.7.4, but I didn't realize the loader version is different.

I'm not sure how to get that version number, but I think I'm on 0.11.6.  This is what I found from some log scanning:
```
$ grep -i loader latest.log
[00:45:32] [main/INFO]: [FabricLoader] Loading 175 mods:
        - fabric-resource-loader-v0@0.4.7+6afaa13c7d
        - fabricloader@0.11.6
```

**Comment by DavD729** [comment]
I Confirm the problem "Crash during initializing server", i'll be fixing this problem today, Thanks for the FeedBack <3
