### ISSUE TITLE
Crashing with Sodium

### ISSUE THREAD

**Issue by frikinjay** [DavD729/AppleTreesRev#9]
Using the latest release of fabric Apple Trees Rev with 0.12.5 fabric loader and latest release of sodium. This is the error.

``` Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'appletreesrev'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at me.steven.indrev.registry.MaterialHelper.withBlock(MaterialHelper.kt:104)
		at me.steven.indrev.registry.IRItemRegistry$registerAll$1.invoke(IRItemRegistry.kt:40)
		at me.steven.indrev.registry.IRItemRegistry$registerAll$1.invoke(IRItemRegistry.kt:38)
		at me.steven.indrev.registry.MaterialHelper.register(MaterialHelper.kt:109)
		at me.steven.indrev.registry.IRItemRegistry.registerAll(IRItemRegistry.kt:50)
		at me.steven.indrev.IndustrialRevolution.onInitialize(IndustrialRevolution.kt:56)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at shetiphian.multibeds.common.block.BlockMultiBedBase.lambda$new$0(BlockMultiBedBase.java:82)
		at shetiphian.core.common.DistExecutor.runWhenOn(DistExecutor.java:58)
		at shetiphian.multibeds.common.block.BlockMultiBedBase.<init>(BlockMultiBedBase.java:80)
		at shetiphian.multibeds.common.block.BlockEarthBed.<init>(BlockEarthBed.java:13)
		at shetiphian.multibeds.Values.builder_blocksEarthBeds(Values.java:52)
		at shetiphian.multibeds.Values.<clinit>(Values.java:46)
		at shetiphian.multibeds.MultiBeds.onInitialize(MultiBeds.java:40)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at shetiphian.platforms.common.block.BlockPlatformBase.lambda$new$0(BlockPlatformBase.java:113)
		at shetiphian.core.common.DistExecutor.runWhenOn(DistExecutor.java:58)
		at shetiphian.platforms.common.block.BlockPlatformBase.<init>(BlockPlatformBase.java:111)
		at shetiphian.platforms.common.block.BlockPlatformType$Walkways.<init>(BlockPlatformType.java:67)
		at shetiphian.platforms.common.block.BlockPlatformFlat.<init>(BlockPlatformFlat.java:16)
		at shetiphian.platforms.Values.builder_blocksPlatforms(Values.java:50)
		at shetiphian.platforms.Values.<clinit>(Values.java:45)
		at shetiphian.platforms.Platforms.onInitialize(Platforms.java:30)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at net.id.aether.util.RenderUtils.cutoutMippedRenderLayer(RenderUtils.java:48)
		at net.id.aether.blocks.AetherBlockActions.lambda$static$5(AetherBlockActions.java:30)
		at net.id.incubus_core.util.RegistryQueue.register(RegistryQueue.java:46)
		at net.id.incubus_core.util.RegistryQueue.register(RegistryQueue.java:38)
		at net.id.aether.blocks.AetherBlocks.init(AetherBlocks.java:310)
		at net.id.aether.Aether.onInitialize(Aether.java:68)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at net.thegrimsey.transportables.TransportablesBlocks.RegisterBlockRenderLayerMap(TransportablesBlocks.java:57)
		at net.thegrimsey.transportables.TransportablesBlocks.RegisterBlock(TransportablesBlocks.java:52)
		at net.thegrimsey.transportables.TransportablesBlocks.RegisterBlocks(TransportablesBlocks.java:37)
		at net.thegrimsey.transportables.Transportables.onInitialize(Transportables.java:16)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_1921
		at party.lemons.trapexpansion.block.SpikeTrapBlock.<init>(SpikeTrapBlock.java:54)
		at party.lemons.trapexpansion.init.TrapExpansionBlocks.<clinit>(TrapExpansionBlocks.java:15)
		at party.lemons.trapexpansion.TrapExpansion.onInitialize(TrapExpansion.java:15)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5944 failed
	at net.minecraft.class_4668.<clinit>(class_4668.java:125)
	at dav.mod.init.BlockInit.renderBlocks(BlockInit.java:64)
	at dav.mod.init.BlockInit.<clinit>(BlockInit.java:119)
	at dav.mod.init.ItemInit.<clinit>(ItemInit.java:108)
	at dav.mod.AppleTreesRev.onInitialize(AppleTreesRev.java:24)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_5944 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:224)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
	... 20 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetUniformLocation(ILjava/lang/CharSequence;)I in sodium.mixins.json:features.shader.MixinShader from mod sodium failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.sodium.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 23 more ```

**Comment by DavD729** [comment]
I'm Already checking what happend here, thanks for the Feedback <3

**Comment by DavD729** [comment]
Wich Version of Minecraft is?
